### ISSUE TITLE
Migrate pdp_util to modelmeta 0.3.0

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/pdp_util#15]
We would like to migrate `pdp_util` to `modelmeta` 0.3.0. The reasons for this are:

1. Later releases of `modelmeta` contain features we wish to have available for operating with `pcic_meta`. (Currently, chunking; later no doubt other things.)
1. `pcic_meta` is in a pre-migration state. It is not feasible to continue with this situation, namely using ad-hoc versions of `modelmeta` and its associated tooling to handle this.
1. We do not want to release special versions of `modelmeta` that to deal with this situation.
1. Therefore we would like to migrate the `pcic_meta` database to the latest migration, which is compatible with `modelmeta` 0.3.0. 
1. And so we must update `pdp_util` to use `modelmeta` 0.3.0. 

The changes necessary appear to be confined to [`pdp_util/pdp_util/raster.py`](https://github.com/pacificclimate/pdp_util/blob/master/pdp_util/raster.py) and to be simple.

**Comment by rod-glover** [comment]
Classes used in `pdp_util/pdp_util/raster.py`. Changes needed for migration to 0.3.0.

| 0.2.0 | 0.3.0 | Comments |
|-| -| -|
| DataFile | DataFile| No change. Verified. |
| DataFileVariable |DataFileVariableDSGTimeSeries | Change name of class only |
| EnsembleDataFileVariables | EnsembleDataFileVariables | No change. Verified. |
| Ensemble | Ensemble | No change. Verified. |
| VariableAlias | VariableAlias | No change. Verified. |

**Comment by rod-glover** [comment]
`modelmeta` is also used in `pdp_util/ensemble_members.py`.

| 0.2.0 | 0.3.0 | Comments |
|-|-|-|
| Ensemble | Ensemble | No change. Verified. |

**Comment by rod-glover** [comment]
Changes to the queries issued by ` are trivial. 

What is less trivial is the testing harnesses in `pdp_util`: Tests for `pdp_util/raster.py` and `pdp_util/ensemble_members.py` depend on a database defined and set up in `modelmeta`. That database, `modelmeta/data/mddb-v1.sqlite`, was evidently founded on the ORM defined in `modelmeta/v1`, which is now defunct (modelmeta has been using ORM `v2` since version 0.0.7).

There are two obvious alternatives at this point: 
1. Use a modelmeta `v2` database, `modelmeta/data/mddb-v2.sqlite`, whose contents are at this point unknown. Although one can see the convenience of it, it is in general unwise to have your test setup depend on data provided by another package whose purposes may diverge from your own.
2. Define test data in `pdp_util` test fixtures and stop borrowing data from `modelmeta`. This is a more standard practice.

I prefer alternative 2.

**Comment by jameshiebert** [comment]
Yeah, with `testing.postgresql` being quite good now, we've pretty much moved away using sqlite for any testing at all. I'd prefer alternative 2 as well.
